# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o wallbox_nord_pool_linux_amd64

      - name: Build linux arm
        run: GOOS=linux GOARCH=arm GOARM=5 go build -o wallbox_nord_pool_linux_arm

      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "wallbox_nord_pool_linux_amd64,wallbox_nord_pool_linux_arm"
